### ISSUE TITLE
Fresh install creates two accounts

### ISSUE THREAD

**Issue by Puyodead1** [YouPHPTube/YouPHPTube-Encoder#137]
![image](https://user-images.githubusercontent.com/14828766/56610931-9f397a00-65de-11e9-8ab8-24e064f553a7.png)
The admin user doesnt work as the password is in plain text... so i have to edit the mysql to get admin

**Comment by DanielnetoDotCom** [comment]
you can delete the row with plain text, it will be fixed in future releases
