### ISSUE TITLE
How can we improve encoding speed

### ISSUE THREAD

**Issue by honeyfairy** [YouPHPTube/YouPHPTube-Encoder#138]
As you can see in the pic, there is still free resources. So cant we use ALL resources to speed up encoding. It encodes one by one. Can it not encode 5 or 10 at a time?
![Capture](https://user-images.githubusercontent.com/17691989/56843113-287dd480-689d-11e9-923b-8cff5b536d8a.PNG)

**Comment by DanielnetoDotCom** [comment]
The encoder will encode only 1 at a time if you encode more then one the server will share resources and you will encode each one on the double of the time.

you are probably not using full CPU due to some other bottleneck, maybe the disk IO

**Comment by honeyfairy** [comment]
I dont understand this:

> The encoder will encode only 1 at a time if you encode more then one the server will share resources and you will encode each one on the double of the time.

What does  "will encode each one on the double of the time" mean?

How can I confirm this?
How can encoding speed be improved?
