### ISSUE TITLE
Encode videos from command line

### ISSUE THREAD

**Issue by honeyfairy** [YouPHPTube/YouPHPTube-Encoder#139]
I have a batch of videos that i upload to a certain folder on my server daily.
So, every day new videos are added to: `/itec/staff/videos/` folder

Now, how can I automatically set Youphptube to encode the new videos that are found in that folder daily?

I thought about a cronjob if it is possible to encode from the command line.

Please let me know

**Comment by DanielnetoDotCom** [comment]
I am not sure how to do it, but I am sure it is possible, you probably have to create a script to do it.

if you want you can hire us to create this script for you.

**Comment by HauptJ** [comment]
@honeyfairy you can use a cronjob and a script to call ffmpeg to encode the videos. 

https://gist.github.com/tayvano/6e2d456a9897f55025e25035478a3a50

**Comment by honeyfairy** [comment]
> @honeyfairy you can use a cronjob and a script to call ffmpeg to encode the videos.
> 
> https://gist.github.com/tayvano/6e2d456a9897f55025e25035478a3a50

Yes, but how will it then be added to the Youphptube database and the thumbnails created etc?

**Comment by honeyfairy** [comment]
> I am not sure how to do it, but I am sure it is possible, you probably have to create a script to do it.
> 
> if you want you can hire us to create this script for you.

I will email you for a quote on this now. Thank you

**Comment by honeyfairy** [comment]
> I am not sure how to do it, but I am sure it is possible, you probably have to create a script to do it.
> 
> if you want you can hire us to create this script for you.

I have emailed you on your gmail address. No response as yet

**Comment by DanielnetoDotCom** [comment]
quote sent
