### ISSUE TITLE
Auto delete video after encoding

### ISSUE THREAD

**Issue by honeyfairy** [YouPHPTube/YouPHPTube-Encoder#140]
How do I set the encoder to delete the original video file after encoding it?

To be clear:
I have this video
**/media/videos/How-to-setup-something.mkv**

So when i go to Bulk encode and the encoder picks up the file and completes encoding then it should delete the file **/media/videos/How-to-setup-something.mkv**

**Comment by DanielnetoDotCom** [comment]
we do not have this option yet
