### ISSUE TITLE
Your system path to application can not be empty

### ISSUE THREAD

**Issue by k7n2g** [YouPHPTube/YouPHPTube-Encoder#151]
Can anyone tell me what i have missed with this install of encoder please  i get ERROR : Your system path to application can not be empty  i have /var/www/html/YouPHPTube/ 
 have done sudo nano /etc/apache2/apache2.conf   all   Rewrite enabled  apache restarted

**Comment by DanielnetoDotCom** [comment]
can you please screenshot where are you getting this error?

I have never seen this before

**Comment by k7n2g** [comment]
Hi Daniel have reuploaded   got this Error Three times with three different VPS installs  this is Fourth install on another vps  i now have it stuck at processing i followed all your install instructions as per Doc   obviously i have something wrong  https://www.screencast.com/t/V7iFJvAdE8j  any help is appreciated Dave

**Comment by k7n2g** [comment]
Hi sorted apparently this is not an encoder problem but  a streamer site problem to do with domain name
encoder was looking for http://www.domain.com/YouPHPTube    when streamer site is http://domain.com
This was why it was saying " Your system path to application can not be empty"  thanks for the help guys Dave
