### ISSUE TITLE
Customize encoder options ?

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube-Encoder#152]
Hello

1)How can I customize the encoder option ? I know going to encoder on configuration you can change some setting . But where those setting are actually stored ; on witch folder ? For example I don't like the name you gave to each resolution ''LOW , SD , HD '' , it's very old . The viewer can't even know if HD is 720p, 1080p or witch one .
2) How to change the bitrate of the encoded files ? Some downloaded videos from youtube are x3 times more heavier than the original size , and I'm running the encoder at medium preset

**Comment by DanielnetoDotCom** [comment]
Hi 

the LOW , SD , HD are only for the file names

you can customize the switch labels on the Resolution Switch plugin


![image](https://user-images.githubusercontent.com/18009293/60722813-553b1180-9f08-11e9-8807-4aff9ae0e663.png)

**Comment by ExeCRabLE2** [comment]
We also need to customize the encoder settings, because we need a better quality. In all encoder pictures, i found, i see the menu option "configuration", but in my installation i don't see the option.

**Comment by DanielnetoDotCom** [comment]
check this https://github.com/YouPHPTube/YouPHPTube-Encoder/issues/58
