### ISSUE TITLE
Additional admin options missing

### ISSUE THREAD

**Issue by sipero** [YouPHPTube/YouPHPTube-Encoder#156]
Hi,

The additional options are missing this is what I have
https://nimb.ws/F2Y90A

**Comment by DanielnetoDotCom** [comment]
I just answer you this 

Please check those

YouPHPTube/YouPHPTube-Encoder#145

YouPHPTube/YouPHPTube-Encoder#124

**Comment by sipero** [comment]
Hi,

This fixed the issue for the admin user but from what is described I need to create a user with admin access to have these features and then a default user that won't have access to the extra options.

**Comment by DanielnetoDotCom** [comment]
The encoder admin is the first user you used to log in.

streamer admin does not mean it will be an encoder admin.

**Comment by sipero** [comment]
Thanks I installed phpmyadmin on my VPS so I can better control this. Thanks
