### ISSUE TITLE
HLS Version

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube-Encoder#157]
I have a stupid question. I now use the version 2.3 of the encoder. It's the last version, before HLS support.
Where can I find the encoder versions, with the HLS support?

greeting

**Comment by DanielnetoDotCom** [comment]
First, you need to update your encoder using git pull https://github.com/YouPHPTube/YouPHPTube/wiki/How-to-Update-your-YouPHPTube


also, make sure your streamer is up to date.

**Comment by Donnerstein** [comment]
Thank you that works So, why is not it the newest version, if I download it as a zip file on the Brwoser, and then unzip it in the directory.

**Comment by DanielnetoDotCom** [comment]
yeah, maybe in the future :)

**Comment by DanielnetoDotCom** [comment]
I always recommend to install it using the git clone command
