### ISSUE TITLE
Set Video Status as Inactive when direct upload a video on youPHPtube

### ISSUE THREAD

**Issue by iqbalzain997** [YouPHPTube/YouPHPTube-Encoder#158]
I am setting videos on youPHPtube. During this, I was stuck in a little issue. I want Every uploaded video status as inactive instead of active. After that Admin can change the status of the video.

I have a lot of search about it and found a single thing which is that after encoding, the status of video can be changed by going to Settings > General settings > Encoder > makeVideosInactiveAfterEncode, But I need this after direct upload.

**Comment by DanielnetoDotCom** [comment]
I just tested and it is working as expected, where did you notice it?

**Comment by iqbalzain997** [comment]
Hi,
Thanks for coming back to me.
Yes, This is working only after encoding the video. But I need it after direct upload. I have never get it working after direct upload.
thanks

**Comment by DanielnetoDotCom** [comment]
Can you please try it on demo site??

**Comment by iqbalzain997** [comment]
Hi DanielnetoDotCom,
I really appreciate your time for my issue.
I think there is the mis-confusion here. I want every video status as inactive when It uploads by direct upload button. Now on demo site also, the default status of every uploaded video is active.
Hope you will understand me.
Many thanks

**Comment by DanielnetoDotCom** [comment]
can you please check how is your configuration on the plugin menu.


![image](https://user-images.githubusercontent.com/18009293/61225000-10785d00-a6f6-11e9-8405-21dd5b51a91c.png)

**Comment by iqbalzain997** [comment]
Yes, I have set it. and It is working after encoding.
![general](https://user-images.githubusercontent.com/37999815/61225499-1db73b00-a73a-11e9-84de-466450aedbe0.png)

**Comment by DanielnetoDotCom** [comment]
Please make sure it is checked on the plugin menu, NOT admin menu.

**Comment by iqbalzain997** [comment]
Hi,
Can you please direct me how can I go to the plugin menu?
thanks

**Comment by DanielnetoDotCom** [comment]
Left sandwich menu -> plugins

![image](https://user-images.githubusercontent.com/18009293/61228935-951aa980-a6fd-11e9-90de-4f9969cb0dce.png)

**Comment by iqbalzain997** [comment]
I really appreciate your help.
This works like a charm :)
Many Thanks
Regards,
zain
