### ISSUE TITLE
Encoding video / Resolution switcher 

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube-Encoder#159]
So , when you visit the encoder page , you have 3 option to encode .
In case you choose 3 of them , are you gonna have the switch option working ?

Isn't this a wast of space/storage ? Why there's no HLS ? As far as I've seen , there's no HLS support on this project , ( maybe for live streaming , but that obvious ) .
In case ( future updates ) , if there's a HLS support , is the plugin still gonna work ? ( Resolution switcher )

**Comment by DanielnetoDotCom** [comment]
Hi, 

You are correct, If you do not have the VideoResolutionSwitcher plugin, encode all resolutions is a waste of space.

If you have the VideoHLS plugin you do not need the VideoResolutionSwitcher, because HLS videos switch the resolutions automatically

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom But where do I get from the VideoHLS plugin ?

**Comment by akhilleusuggo** [comment]
I just saw that you have updated the plugins
