### ISSUE TITLE
Bulk encode from CLI

### ISSUE THREAD

**Issue by christianreiss** [YouPHPTube/YouPHPTube-Encoder#160]
Hey,

the bulk button does nothing; tested for months in different versions, it's just dead.
I tried chrome, firefox, edge to no avail.

But maybe a better solution would be to be able to import a folder directly on the server via the command line. This would skip all the webinterface quirks, php limits et all.

Would this be hard to code in?

**Comment by DanielnetoDotCom** [comment]
Hi, did you follow this?

https://github.com/YouPHPTube/YouPHPTube/wiki/Bulk-Upload-Videos

**Comment by christianreiss** [comment]
Yes.

Well that's more of a "how to use file transfer" but yes. 
Still, the bulk button does nothing- always.

**Comment by DanielnetoDotCom** [comment]
you are probably missing something.

try to check the directory permissions

**Comment by akhilleusuggo** [comment]
@christianreiss You can move a directory of course . just move it with command line , I did it and it's working . You can even put that directory on the web folder ( not recommended ) , I tested it and working 10/10

**Comment by christianreiss** [comment]
Yeah... No.

[https://misc.alpha-labs.net/bulk.gif](url)

No button does anything. Really. All options under bulk are dead. Updating further (to master) makes everything broken, even single uploads.

**Comment by akhilleusuggo** [comment]
@christianreiss Link the logs
I will risk it and say you didn't gave enough permission to the location file , so the server can't get to that location .

So you gonna do this :
1- `mkdir /var/www/html/myvideos` ( as an example ) , y directory are different , just following the picture you have sent )
Now that you have created the directory , give it the permission to read and write 
2- `chmod 777 /var/www/html/myvideos`
You have just created and gave the directory permissions , now move the videos to the location
 3- Before moving the video , check that directory has videos
`ls /var/www/html/myvideos ` ( or wherever you have your videos )
The output should show the name of your videos
4- Move your videos to the right directory that we have created on step 1 , to do that , we need to be on the videos directory where you had your videos 
`cd /var/www/html ` press Enter 
`mv * /var/www/html/myvideos`
`mv` means move , `*` means all
5- Go to your encoder and enter the location of the Step 1 , should work 100%
6- Optative : Remove the videos from the location you had before
Use the command `rm` to remove

**Comment by christianreiss** [comment]
Hey,

sorry for the long delay. Real life was demanding.
Thank you for the detailed steps; but unless I really screwed up somwhere bad 20+ years of Linux administrating got me there already.

Like I showed in the gif above: The client (browser) does not send any request to the server. So there is no access_log, no error_log, no youphptube.log. Single file upload works, the rest does not.

Using Firefox, Linux and no kind of flash.  I know its 2010+ but I thought in the off chance I mention this.

**Comment by akhilleusuggo** [comment]
@christianreiss You need to check the log of the encoder not the streaming server

**Comment by christianreiss** [comment]
Yes. I am fully aware and did that.

**Comment by christianreiss** [comment]
Humm.

I switched 
- from PHP 7.0 to 7.2 (remi),
- from apache2 to nginx
- updated to the latest commit.

Now it works. I can't say what part solved it, but now it works.
Thank you too all who supported.

**Comment by akhilleusuggo** [comment]
@christianreiss that's mean you're using ubuntu 18.04 ( you haven't specified that )

**Comment by christianreiss** [comment]
I am unsure how you came to the Ubuntu conclusion, mind sharing?

Hint: I am afraid you might not be correct there. Remi is a PHP7 repository for CentOS, so I am using CentOS7.

**Comment by akhilleusuggo** [comment]
it's just that this script is for ubuntu . if you have the php 7.0 on ubuntu 18.04  is not gonna work well . When you mentioned 7.2 I understood that you have installed the right version , since the wiki is very outdated and it ask to install php 7.0
