### ISSUE TITLE
Religious / Political statements

### ISSUE THREAD

**Issue by christianreiss** [YouPHPTube/YouPHPTube-Encoder#161]
This software has reached a point that it really needs to gain a professional momentum.
Non-relevant (to the software) statements should be removed; it's about the software not about the views of believes from the man behind.

Always remember that things you will like/love others might find offensive. And the other way around. Also "Not to be used for Evil" is a matter of view. Freeing poorer countries from oppressors, giving them democracy and securing their oil fields is good for some. The same action might be considered Evil from another man's perspective.

Personal believes and views belong in a blog. This is the very reason why all the big(ger) companies explicitly forbid any those statements.

Thank you for your consideration,
and please dont be offendend,
I am trying to do good. Not Evil.

**Comment by DanielnetoDotCom** [comment]
@christianreiss thanks, but I will keep the "Not for evil" statement.
