### ISSUE TITLE
Share Videos From File

### ISSUE THREAD

**Issue by acemile** [YouPHPTube/YouPHPTube-Encoder#163]
When I click on '+ Add files' green button; then, selecting the files and click 'open', the dialog box closes and no files show under the form for uploading. I looked at the console for errors and I found the following, can someone direct me to where I can find the cause of this issue.

jQuery.Deferred exception: Cannot read property 'createObjectURL' of undefined TypeError: Cannot read property 'createObjectURL' of undefined
    at $.<computed>.<computed>.loadVideo (http://10.10.1.123/encoder/view/jquery-file-upload/js/jquery.fileupload-video.js:89:37)
    at $.<computed>.<computed>.func (http://10.10.1.123/encoder/view/jquery-file-upload/js/jquery.fileupload-process.js:84:65)
    at j (http://10.10.1.123/encoder/view/js/jquery-3.2.0.min.js:2:29999)
    at k (http://10.10.1.123/encoder/view/js/jquery-3.2.0.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
add @ jquery-3.2.0.min.js:2
(anonymous) @ jquery-3.2.0.min.js:2
Deferred @ jquery-3.2.0.min.js:2
then @ jquery-3.2.0.min.js:2
(anonymous) @ jquery.fileupload-process.js:90
each @ jquery-3.2.0.min.js:2
_processFile @ jquery.fileupload-process.js:78
(anonymous) @ jquery.ui.widget.js:148
func @ jquery.fileupload-process.js:153
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
add @ jquery-3.2.0.min.js:2
(anonymous) @ jquery-3.2.0.min.js:2
Deferred @ jquery-3.2.0.min.js:2
then @ jquery-3.2.0.min.js:2
(anonymous) @ jquery.fileupload-process.js:157
each @ jquery-3.2.0.min.js:2
process @ jquery.fileupload-process.js:146
(anonymous) @ jquery.ui.widget.js:148
(anonymous) @ jquery.ui.widget.js:260
each @ jquery-3.2.0.min.js:2
each @ jquery-3.2.0.min.js:2
$.fn.<computed> @ jquery.ui.widget.js:240
(anonymous) @ jquery.fileupload-ui.js:116
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
fire @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
(anonymous) @ jquery-3.2.0.min.js:2
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
add @ jquery-3.2.0.min.js:2
(anonymous) @ jquery-3.2.0.min.js:2
Deferred @ jquery-3.2.0.min.js:2
then @ jquery-3.2.0.min.js:2
j @ jquery-3.2.0.min.js:2
k @ jquery-3.2.0.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.0.min.js:2
i @ jquery-3.2.0.min.js:2
add @ jquery-3.2.0.min.js:2
(anonymous) @ jquery-3.2.0.min.js:2
Deferred @ jquery-3.2.0.min.js:2
then @ jquery-3.2.0.min.js:2
data.process @ jquery.fileupload.js:669
add @ jquery.fileupload-ui.js:115
(anonymous) @ main.js:29
i @ jquery-3.2.0.min.js:2
fireWith @ jquery-3.2.0.min.js:2
A @ jquery-3.2.0.min.js:4
(anonymous) @ jquery-3.2.0.min.js:4
load (async)
send @ jquery-3.2.0.min.js:4
ajax @ jquery-3.2.0.min.js:4
r.<computed> @ jquery-3.2.0.min.js:4
getJSON @ jquery-3.2.0.min.js:4
add @ main.js:25
_trigger @ jquery.ui.widget.js:701
(anonymous) @ jquery.fileupload.js:1057
each @ jquery-3.2.0.min.js:2
_onAdd @ jquery.fileupload.js:1050
(anonymous) @ jquery.ui.widget.js:148
(anonymous) @ jquery.fileupload.js:1256
i @ jquery-3.2.0.min.js:2
add @ jquery-3.2.0.min.js:2
always @ jquery-3.2.0.min.js:2
_onChange @ jquery.fileupload.js:1246
(anonymous) @ jquery.ui.widget.js:148
handlerProxy @ jquery.ui.widget.js:610
dispatch @ jquery-3.2.0.min.js:3
q.handle @ jquery-3.2.0.min.js:3
jquery-3.2.0.min.js:2 jQuery.Deferred exception: Cannot read property 'undefined' of undefined TypeError: Cannot read property 'undefined' of undefined
    at $.<computed>.<computed>.validate (http://10.10.1.123/encoder/view/jquery-file-upload/js/jquery.fileupload-validate.js:91:38)
    at func (http://10.10.1.123/encoder/view/jquery-file-upload/js/jquery.fileupload-process.js:84:65)
    at j (http://10.10.1.123/encoder/view/js/jquery-3.2.0.min.js:2:29999)
    at k (http://10.10.1.123/encoder/view/js/jquery-3.2.0.min.js:2:30313) undefined

**Comment by DanielnetoDotCom** [comment]
I am not sure what do you mean but looks like it is not loading your Jquery

**Comment by acemile** [comment]
> I am not sure what do you mean but looks like it is not loading your Jquery

Yeah you were right. For a reason the JavaScript library hosted externally didn't load due to CORB in Chrome. 

It has been fixed after hosting the scripts locally.
