### ISSUE TITLE
Can I prevent the encoder from translating Chinese characters to Latin characters?

### ISSUE THREAD

**Issue by linuxbabe** [YouPHPTube/YouPHPTube-Encoder#167]
I can upload Chinese-titled videos from my desktop computer to YouPHPTube just fine, because I can manually enter the title. However, if I try to import Chinese-titled videos from local folders on the server, the Encoder will translate the title to Latin characters, which doesn't work. The title become gibberish and the videos can't be imported as a result. 

![youphptube encoder](https://user-images.githubusercontent.com/15121670/62916447-159afb80-bdcb-11e9-8e95-3e42639bb76c.png)

How can I make the encoder use the original Chinese titles?

**Comment by akhilleusuggo** [comment]
I'm trying to find the answer to that 2 months .... And my only doubt it's the DB

**Comment by DanielnetoDotCom** [comment]
On the image @linuxbabe pasted above is not from DB, it is a PHP script that scan the directory

Maybe this happen because we are using utf8_encode

https://github.com/YouPHPTube/YouPHPTube-Encoder/blob/3df9e4e158600e98b5d46af94557971acabee685/view/listFiles.json.php#L25

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom yeh , but even after the encoding has ended , the video still looking with the same symbols. <Same thing with russian letters .

**Comment by DanielnetoDotCom** [comment]
I mean, it may work if remove the utf8_encode function

I am not sure, but the utf8 function is there for some reason, and if remove it may fail in other characters type.

**Comment by linuxbabe** [comment]
What function should I use instead? This YouPHPTube instance is only for personal use, so I don't mind losing support for other character types.

**Comment by DanielnetoDotCom** [comment]
just remove the function.

replace ...

`$obj->path = utf8_encode($value); `

to this

`$obj->path = ($value); `

**Comment by linuxbabe** [comment]
Ok. So I have removed the function and use variables directly. 
```
                $obj->path = $value;
                $obj->name = $path_parts['basename'];
```
And the bulk encoder can display Chinese characters, although it's not perfect. Some characters can't be displayed, but I'm happy with it.  

![Selection_001](https://user-images.githubusercontent.com/15121670/63097532-42097000-bfa3-11e9-9f73-1f1413f25814.png)

**Comment by DanielnetoDotCom** [comment]
I guess, it will work for you but may fail in some cases.

**Comment by akhilleusuggo** [comment]
@DanielnetoDotCom Sorry for the late question after closing the topic . Could you please specify where exactly is that file located ? Thanks

**Comment by linuxbabe** [comment]
Go to the YouPHPTube encoder web root directory, then go to the **view** sub-directory.

**Comment by DanielnetoDotCom** [comment]
YouPHPTube-Encoder/view/listFiles.json.php

**Comment by akhilleusuggo** [comment]
thank you guys :)
