### ISSUE TITLE
Strange fix ?

### ISSUE THREAD

**Issue by akhilleusuggo** [YouPHPTube/YouPHPTube-Encoder#169]
I'm having multiple encoders ( not hosted on the same streaming site ) . I well knows issue is that , you can't follow the progress of the encoded video if encoder and the streamer site are not on the same server . Suddenly today , I'm using one of my external encoders and I can follow up with the progress . Have you fixed it , or it's just magic ? xD

**Comment by DanielnetoDotCom** [comment]
LOL, nothing changed, maybe magic :)

but I guess it the file is encoding on the same recommended encoder you will see the progress.

**Comment by akhilleusuggo** [comment]
I see .. Cause i saw you updated the 7.4 and I though you found some way to fix it . Thanks for the info :)
