### ISSUE TITLE
Encoder - sorry we could not find your streamer site

### ISSUE THREAD

**Issue by achaiah** [YouPHPTube/YouPHPTube-Encoder#175]
So before I get flamed, I read all the solutions proposed in the previous tickets and none of them work. Something is still broken with the Encoder.

1. I do NOT use https so all my sites are http only (to avoid the ssl issue)
2. I already set allow_url_fopen = On  allow_url_include = On
3. I am running a single docker image with YouPHPTube and Encoder installed together, just using a different path.  I published my image [on dockerhub](https://hub.docker.com/r/achaiah/youphptube)
4. I'm using my host machine IP address directly instead of FQDN since I want to run both on my internal network.

...and it's not working. What else should I try? Why is this such a pain to begin with.. I'm supplying a direct IP address so there shouldn't be any issues...

Thanks

**Comment by DanielnetoDotCom** [comment]
please check your log file

the encoder log and the streamer log

**Comment by achaiah** [comment]
I rebuilt the docker image with different options and the problem has gone away. I think it's probably the `allow_url_fopen = On allow_url_include = On` issue but not sure.
