### ISSUE TITLE
Improvements for YouPHPtube Encoder

### ISSUE THREAD

**Issue by maxlinux2000** [YouPHPTube/YouPHPTube-Encoder#176]
In the initial wizard there are some errors and improvements that not allow the user to install an encoder server much faster.

Add a control of the version of youtube-dl is missing and if it is installed. I had an old version and it took me a while to understand why it didn't work.

The ffmpeg version control is missing (for example in ubuntu 16.04 by default there is version 2.8, and 3.x is needed)

In the wizard it is proposed to increase the upload size of the files to 100MB in php.ini, while in other documents there is talk of 1000MB ... a zero is missing.

The console commands would be appreciated, to copy and paste and thus change these values from the terminal.

**Comment by DanielnetoDotCom** [comment]
Thank you, done
