### ISSUE TITLE
Public encoder crashed

### ISSUE THREAD

**Issue by jorgeiglesiasca** [YouPHPTube/YouPHPTube-Encoder#177]
Public encoder seems stuck with a video on downloading 0% forever

**Comment by DanielnetoDotCom** [comment]
Thank you, fixed.

**Comment by jorgeiglesiasca** [comment]
Hello.  I think is stuck again .  No video transferred to the server after conversion and very slow upload

**Comment by DanielnetoDotCom** [comment]
Since yesterday, you will need to update your streamer and plugins to be able to use the public encoder
