### ISSUE TITLE
Formatting problems with the video description

### ISSUE THREAD

**Issue by Donnerstein** [YouPHPTube/YouPHPTube-Encoder#187]
Hi
I had the update recorded, since then, the formatting of the video description, from the encoder to the steamer is no longer accepted. This is also true on the demo side.

![image](https://user-images.githubusercontent.com/52116237/66741224-4b189f80-ee75-11e9-8d79-6dda882e6a48.png)

![image](https://user-images.githubusercontent.com/52116237/66741239-54097100-ee75-11e9-9188-4d4a07af1a8c.png)

Furthermore, links in the video description are no longer converted to hyperlinks.
On the streamers page after the update, the line breaks have been removed from the video descriptions.

greeting
Donnerstein

**Comment by DanielnetoDotCom** [comment]
try to check this 

![image](https://user-images.githubusercontent.com/18009293/66750717-8dd17c00-ee63-11e9-8088-558804e60a8b.png)

**Comment by Donnerstein** [comment]
Yes, thank you, I did not see that there are new options in the CustomizeAdvanced plugin.
